name: Validate pull request

on:
  pull_request:
    types: [opened, reopened]
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm test via Jest
        run: |
          npm i
          npm test
        env:
          CI: true
